#!/bin/bash

EMERGE_CONF=${EMERGE_CONF:-/etc/emerge}

PACMAN='pacman'

list_doesnot_contain() {
	local target="$1"
	shift
	while [ -n "$1" ]; do
		[ "$target" = "$1" ] && return 1
		shift
	done
	return 0
}

filter_conf() {
	local line
	while read line; do
		if [ -n "$(echo $line|grep '^<')" ]; then
			import_set $(echo $line|sed 's/^<//')
		elif [ -n "$(echo $line|grep '^@')" ]; then
			$PACMAN -Sqg $(echo $line|sed 's/^@//')
		else 
			echo $line
		fi
	done		
}

import_set() {
	local includecmd="$EMERGE_CONF/$1.set"
	local maskcmd="$EMERGE_CONF/$1.mask"

	[ -x "$includecmd" ] || includecmd="cat $includecmd"
	[ -x "$maskcmd" ] || maskcmd="cat $maskcmd"

	local include=$($includecmd|filter_conf)
	local mask=$($maskcmd|filter_conf)
	for pkg in $include; do
		if list_doesnot_contain $pkg $mask ; then
			echo $pkg
		fi
	done
}

extras() {
	local line
	while read line; do
		for pkg in $line; do
			list_doesnot_contain $pkg $@ && echo $pkg
		done
	done
}

explicit=$(import_set world)

explicit_rm=$($PACMAN -Qqe|extras $explicit)
explicit_add=$(echo $explicit|extras $($PACMAN -Qqe))

cat  <<!
The following packages will be added to the explict set:
$explicit_add

The following packages will be removed from the explicit set:
$explicit_rm

press enter to continue, or Ctrl-C to stop.
!
read

toinstall=""
[ -z "$explicit_rm" ] || $PACMAN -D --asdeps $explicit_rm || exit 1
if [ -n "$explicit_add" ]; then
	for pkg in $explicit_add; do
		if $PACMAN -Q "$pkg" > /dev/null 2>&1; then
			$PACMAN -D --asexplicit $pkg
		else
			toinstall="$toinstall $pkg"
		fi
	done
fi
if [ -n "$toinstall" ]; then
	$PACMAN -Su --noconfirm $toinstall || exit 1
else
	$PACMAN -Su --noconfirm
fi
orphans=$($PACMAN -Qqtd)
[ -z "$orphans" ] || $PACMAN -Rs --noconfirm $orphans || exit 1
