#!/bin/bash

PACSYNC_CONF=${PACSYNC_CONF:-/etc/pacsync}
PACSYNC_CACHE=${PACSYNC_CACHE:-/var/cache/pacsync}

list_doesnot_contain() {
	local target="$1"
	shift
	while [ -n "$1" ]; do
		[ "$target" = "$1" ] && return 1
		shift
	done
	return 0
}

filter_conf() {
	local line
	while read line; do
		if [ -n "$(echo $line|grep '^<')" ]; then
			import_set $(echo $line|sed 's/^<//')
		elif [ -n "$(echo $line|grep '^@')" ]; then
			pacman -Sqg $(echo $line|sed 's/^@//')
		else 
			echo $line
		fi
	done		
}

import_set() {
	local include=$(cat $PACSYNC_CONF/$1.set|filter_conf)
	local mask=$(cat $PACSYNC_CONF/$1.mask|filter_conf)
	for pkg in $include; do
		if list_doesnot_contain $pkg $mask ; then
			echo $pkg
		fi
	done
}

extras() {
	local line
	while read line; do
		list_doesnot_contain $line $@ && echo $line
	done
}

for d in $(find $PACSYNC_CONF -exec stat '{}' -c %Y ';'); do
	if expr $d '>' $(stat $PACSYNC_CACHE/explicit.cache -c %Y) > /dev/null; then
		import_set world > $PACSYNC_CACHE/explicit.cache
		break
	fi
done

explicit="cat $PACSYNC_CACHE/explicit.cache"

explicit_rm=$(pacman -Qqe|extras $($explicit))
explicit_add=$($explicit|extras $(pacman -Qqe))

cat  <<!
The following packages will be added to the explict set:
$explicit_add

The following packages will be removed from the explicit set:
$explicit_rm

press enter to continue, or Ctrl-C to stop.
!
read

toinstall=""
[ -z "$explicit_rm" ] || pacman -D --asdeps $explicit_rm || exit 1
if [ -n "$explicit_add" ]; then
	for pkg in $explicit_add; do
		if pacman -Q "$pkg" > /dev/null 2>&1; then
			pacman -D --asexplicit $pkg
		else
			toinstall="$toinstall $pkg"
		fi
	done
fi
[ -z "$toinstall" ] || pacman -Su --noconfirm $toinstall || exit 1
orphans=$(pacman -Qqtd)
[ -z "$orphans" ] || pacman -Rs --noconfirm $orphans || exit 1
